name: Test and Build frontend app

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend
    # paths:
    # - 'frontend/**'

jobs:
  TestAndBuild:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install and Test
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        sudo apt-get update && sudo apt-get install -y xvfb
        sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
        sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
        sudo apt-get -y install imagemagick x11-apps
        Xvfb -ac :99 -screen 0 1280x1024x16 &
        export DISPLAY=:99
        npm install -g @angular/cli
        cd app
        npm install
        ng test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_TOKEN }}
    
    - name: Build and push image
      run: |
        docker build -t ghcr.io/raphaeljpivato/frontend-app:latest .
        docker push ghcr.io/raphaeljpivato/frontend-app:latest