name: Test and Build frontend app

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend
    # paths:
    # - 'frontend/**'

jobs:
  TestAndBuild:
    name: Test and Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install and Test
      run: |
        sudo apt-get update && sudo apt-get -y install npm
        npm install -g @angular/cli
        ng test

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build image
      run: |
        docker build -t frontend-app:1.0 .
        # docker run frontend-app:1.0
        # docker push frontend-app:1.0