name: Test and Build frontend app

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend
    # paths:
    # - 'frontend/**'

jobs:
  TestAndBuild:
    name: Test and Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up nodejs 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Getting dependencies
      run: |
        cd app/
        npm install

    - name: Install and Test
      run: |
        # cd ..
        # apt-get update && apt-get -y install npm
        npm install -g @angular/cli
        ng test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: raphaeljpivato.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push image
      run: |
        docker build -t raphaeljpivato.io/frontend-app:1.0 .
        docker push raphaeljpivato.io/frontend-app:1.0